input:
  name: "metro_vancouver"
  database_path: "/home/kaveh/projects/h3-routing-platform/data/metro_vancouver.duckdb"
  input_schema: "driving"

algorithm:
  sp_method: "HYBRID"
  partition_res: 7
  hybrid_res: 10

duckdb:
  memory_limit: "8GB"
  threads: 10
  fresh_start: true

parallel:
  workers: 10
