input:
  name: "somerset"
  database_path: "../../data"
  input_schema: "driving"

algorithm:
  sp_method: "HYBRID"
  partition_res: 7
  hybrid_res: 10

duckdb:
  memory_limit: "4GB"
  threads: 10
  fresh_start: true

parallel:
  workers: 10
